version: '2'

services:
   wordpress:
     image: luizferreira:wordpress
     ports:
       - "8007:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 172.23.0.2:3306
       WORDPRESS_DB_NAME: luizferreira
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
     networks:
       - dacs2018
networks:
  dacs2018:
    external:
       name: dacs2018